### ISSUE TITLE
Add order for getters and setters

### ISSUE THREAD

**Issue by Erid** [bryanrsmith/eslint-plugin-sort-class-members#2]
Hi, first I'd like to thank you for creating this plugin, it's really useful for our team.

I'd like to propose some other groups for setters and getters, right now they're being interpreted as functions, but we'd like to be able to group them outside of the functions group. There are 4 ways I can think of grouping getters and setters.

* `[getters]`: Only group getters here
* `[setters]`: Only group setters here
* `[getters-and-setters]`: Group them together
* `[getters-and-setters-pairs]`: Group them together by pairs and if a getter has a setter it should go right after the getter

**Comment by bryanrsmith** [comment]
Hi @Erid. Thanks, I'm glad it's useful for you!

Great idea. The `[getters]` and `[setters]` groups will probably only take a few lines of code to add. Grouping by pairs will need a little custom handling, but not too bad. It's a bit of a special case, so maybe a separate option or two would be appropriate for further customizing this?

```js
 [2, {
    "order": [
        "[getters]",
        "[setters]",
        "[getters-and-setters]",
        "[everything-else]"
    ],
    "adjacentAccessors": true, // require getters and setters with the same name to appear adjacent to one another
    "accessorPairPositioning": "getterThenSetter" // require setters to be positioned immediately after their corresponding getters. Or `"setterThenGetter"`, or `"either"`
}]
```

`adjacentGetterSetter` would be redundant when the `["getters-and-setters"]` group is used, but it would allow you to require getters & setters to be grouped together without enforcing a specific position, which could be useful for some.

I will give it some more thought and try to take a look at it this weekend.

**Comment by Erid** [comment]
Thanks for the reply!, that's an even better solution, it's more flexible.

**Comment by bryanrsmith** [comment]
@Erid Sorry for the delay on this. I got it written a week ago & never got around to cleaning it up and publishing until today. It's pretty close to what's posted above, except I used `accessor-pairs` instead of `getters-and-setters`, and `adjacentAccessors` got rolled into `accessorPairPositioning`. It's all covered in the readme. I have not yet added a way to select all getters and setters in any order. Right now you'd have to select getters, setters, and pairs separately. I skipped that for now because I want to add that for all groups, and not just accessors. I'll open a separate issue for it & probably wait until someone needs it.

I did publish it as a breaking change at 1.0.0 because I also removed the default config for compatibility with ESLint 2. Instead it now exports a recommended configuration that matches the previous defaults if you want to use that.

```js
{
  "plugins": [
    "sort-class-members"
  ],
  "extends": ["eslint:recommended", "plugin:sort-class-members/recommended"]
}
``` 

Let me know how it works for you, and if it covers your use case.
